kind: OAuthClient
apiVersion: oauth.openshift.io/v1
metadata:
  name: self-obs-proxy-client
secret: self-obs-proxy-client
redirectURIs:
  - 'https://grafana-central.{{ .Values.domain }}'
grantMethod: auto
